"""add userprofile model

Revision ID: 27a6d3f4d68b
Revises: 8aa0531bc37c
Create Date: 2024-07-16 13:56:39.180465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a6d3f4d68b'
down_revision = '8aa0531bc37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('NIK', sa.String(length=16), nullable=False),
    sa.Column('no_WA', sa.String(length=20), nullable=True),
    sa.Column('no_telp_hp', sa.String(length=20), nullable=True),
    sa.Column('telegram', sa.String(length=50), nullable=True),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('NIK'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
